
SRCS = main.c
LIBS = -lSDL2 -lSDL2_image -lSDL2_ttf ../libft/libft.a
NAME = SDL2
FLAGS = -Wall -Werror -Wextra

all:
	gcc $(SRCS) $(FLAGS) $(LIBS) -o $(NAME)

noflags:
	gcc $(SRCS) $(LIBS) -o $(NAME)